import time
usernamechoice = input("Welcome, what is your name? ")
print("Hello, " + usernamechoice)
time.sleep(1)
print("For the first question to begin the test, guess the number. You get 2 tries. The number ranges from 47 - 63.")
firsttry = input(": ")
if int(firsttry) == 55:
    print("Great Job! I don't know how you managed first try, but nice. Skip the next question then.")
elif int(firsttry) > 55:
    print("Ouch. That's more. Try again!")
else:
    print("Ouch, That's less. Try again!")
time.sleep(1)
secondtry = input(": ")
if int(secondtry) == 55:
    print("Great Job! Your not a bozo.")
elif int(secondtry) > 55:
    print("Get rekt bozo, it was 55")
else:
    print("Get rekt bozo, it was 55")
time.sleep(1)
print("So that was only the first part, or as you may call it, the 'warmup'.")
time.sleep(5)
print("I know, the questions were silly, but again, warump round.")
time.sleep(2)
print("Going any further may result in sensitive questions and answers that are stored until you close this app. You have been warned..")
time.sleep(5)
print("...")
time.sleep(5)
print("Please answer the further with lowercase ONLY. If you don't, the script answers MAY break, and you will be insulted. Thank you.")
time.sleep(5)
print("...")
time.sleep(5)
questionone = input("What is your worst phobia? ")
print("...")
time.sleep(2)
print("Okay, Interesting.")
time.sleep(1)
if questionone == "scopophobia":
    print("They are watching you.")
else:
    print("...")
time.sleep(10)
questiontwo = input("Do you believe in God? ")
if questiontwo == "yes":
    print("That's Great!")
else:
    print("You are not suited for the rest of this test. Not-sorry.")
time.sleep(1)
print("Well Then.")
time.sleep(10)
print("...")
time.sleep(2)
print("Alright, for the next question. What would you do if I were right behind you, staring into your soul from the behind, and watching you as your answering these questions.?")
time.sleep(4)
print("You looked behind you didn't you.")
time.sleep(3)
print("You can't see me, " + usernamechoice)
time.sleep(5)
print("Anyways.")
time.sleep(1)
print("Do you ever forget your surroundings?")
time.sleep(1)
print("Take a look around, and throw your eyes off of the screen.")
time.sleep(5)
print("Did you realize any of that was even there until you looked at it?")
time.sleep(3)
print("Unless you weren't focused, no. You didn't.")
time.sleep(2)
print("And that is my goal.")
time.sleep(2)
print("Focus, " + usernamechoice)
time.sleep(10)
print("Since this is a script, and you are progressing through lines of code inside a console, I can not indicate wether you are in reality focused or not.")
time.sleep(4)
print("So I will just begin again.")
time.sleep(5)
isthisagame = input("Is this application, a game? ")
if isthisagame == "no":
    print("Correct. You may now move on.")
else:
    print("Incorrect. This is a test, not a game.")
time.sleep(2)
print("...")
time.sleep(5)
print("For the next question, if you could kill anyone, or anybody in this world.")
time.sleep(1)
print("Without any, any consequence.")
time.sleep(1)
killanyone = input("Would you do it? ")
if killanyone == "yes":
    print("Everything in this world has a consequence no matter how long into the future it gets you back, or what anybody says, " + usernamechoice)
    time.sleep(3)
    print("You wont get away with anything, and nobody won't find out, no matter how well you hide, " + usernamechoice)
else:
    print("Good. Actions have consequenses, even if there is apparently none.")
time.sleep(3)
print("...")
time.sleep(3)
print("That is all. Thank you for participating in this test. Please do not close the window yet.")
time.sleep(2)
print("Your answers have been stored locally. They will dissapear upon exit.")
time.sleep(3)
print("Made by Crxyli, inspired by 'The Test'.")
time.sleep(1)
print("This window will now close by itself. Thank you.")
time.sleep(10)
print("Thank you for playing!!")